site_name: Î 4U
repo_name: 'cselab/pi4u'
repo_url: 'https://github.com/cselab/pi4u'


pages:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Sampling: examples/sampling.md
      - Postprocessing: examples/post.md
  - Developing: developing.md
  - Performance and Scalability: hpc.md
  - References: references.md

theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'pie_chart'


markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite



extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
