site_name: Î 4U


pages:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Sampling: examples/sampling.md
      - Postprocessing: examples/post.md
  - Developing: developing.md
  - Performance and Scalability: hpc.md
  - References: references.md

theme:
    name: material
    palette:
        primary: 'indigo'
        accent: 'indigo'

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
